version: '3'

services:
  discord-bot:
    build: ./
    image: typescript:latest
    container_name: discord-bot
    restart: always
    volumes:
      - ./:/usr/src                       # Mount the current directory to workdir of the container
    
