name: Discord Bot CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test the Bot 
    runs-on: ubuntu-latest
    steps:

      # ---------------------------------------------- #
      - name: Checkout the Latest Commit in Master
        uses: actions/checkout@v3
      
      # ---------------------------------------------- #
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      # ---------------------------------------------- #
      - name: Install NPM Dependencies
        working-directory: ./
        run: npm install
      
      # ---------------------------------------------- #
      - name: Test the Bot
        working-directory: ./
        run: npm run test
      